/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Control.ControlCliente;
import Control.ControlDetalleVenta;
import Control.ControlPersona;
import Control.ControlPlataforma;
import Control.ControlVendedor;
import Control.ControlVenta;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author Mauricio
 */
public class GUIDetalleVenta extends javax.swing.JFrame {
    Control.ControlDetalleVenta cdv=new ControlDetalleVenta();
    Control.ControlPlataforma cp=new ControlPlataforma();
    Control.ControlVenta cv=new ControlVenta();
    
    DefaultTableModel dtmDetVenta;
    DefaultTableModel dtmBusqueda;
    String[] tablaDetVenta={"Codigo","Abono","saldo", "Codigo Venta"};
    String[] tablaBusqueda={"Codigo","Abono","saldo", "Codigo Venta"};
    
    String CODIGO_DETALLE_VENTA="";
    int ABONO=0;
    int SALDO=0;
    String CODIGO_VENTA="";
        
    public GUIDetalleVenta() {
        Object[][] data= cdv.consultarDetalleVenta();
        dtmDetVenta=new DefaultTableModel(data, tablaDetVenta);
        dtmBusqueda=new DefaultTableModel(data, tablaBusqueda);
        initComponents();  
        
        
    }
    public void actualizarTablaDetalleVenta(String codigo_detalle_venta){
        Object data[][] = cdv.consultarDetalleVentaCodigo(codigo_detalle_venta);
        dtmDetVenta= new DefaultTableModel(data,tablaDetVenta);
        
        tblDetVenta.setModel(dtmDetVenta);        
    }
    
    public void refrescarTblDetalleVenta(){
        Object[][] data= cdv.consultarDetalleVenta();
        dtmDetVenta=new DefaultTableModel(data, tablaDetVenta);
        tblDetVenta.setModel(dtmDetVenta);
    }
    
    
   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelDetVenta = new javax.swing.JPanel();
        jPanelDatoscli = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        txtcodigodetvnt = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtabonodetvnt = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtcodvnt = new javax.swing.JTextField();
        jPanelbotonesDetVenta = new javax.swing.JPanel();
        btnGuardardetvnt = new javax.swing.JButton();
        btnEliminardetvnt = new javax.swing.JButton();
        btnmostrardetvnt = new javax.swing.JButton();
        jPaneltblDetVenta = new javax.swing.JScrollPane();
        tblDetVenta = new javax.swing.JTable();
        jPanelBusquedaDetVenta = new javax.swing.JPanel();
        txtBusquedaDetVenta = new javax.swing.JTextField();
        btnBusquedaDetVenta = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jCBoxBusquedaDetVenta = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelDetVenta.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Cliente"));

        jPanelDatoscli.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Ingresar Datos"));

        jLabel12.setText("Cod Det Venta:");

        jLabel13.setText("Abono:");

        txtabonodetvnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtabonodetvntActionPerformed(evt);
            }
        });

        jLabel15.setText("Codigo Venta:");

        txtcodvnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcodvntActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelDatoscliLayout = new javax.swing.GroupLayout(jPanelDatoscli);
        jPanelDatoscli.setLayout(jPanelDatoscliLayout);
        jPanelDatoscliLayout.setHorizontalGroup(
            jPanelDatoscliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatoscliLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDatoscliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDatoscliLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelDatoscliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtcodigodetvnt, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                            .addComponent(txtabonodetvnt)))
                    .addGroup(jPanelDatoscliLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(15, 15, 15)
                        .addComponent(txtcodvnt, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanelDatoscliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelDatoscliLayout.createSequentialGroup()
                    .addGap(6, 6, 6)
                    .addComponent(jLabel12)
                    .addContainerGap(199, Short.MAX_VALUE)))
        );
        jPanelDatoscliLayout.setVerticalGroup(
            jPanelDatoscliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDatoscliLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(txtcodigodetvnt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatoscliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtabonodetvnt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelDatoscliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtcodvnt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(101, Short.MAX_VALUE))
            .addGroup(jPanelDatoscliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelDatoscliLayout.createSequentialGroup()
                    .addGap(27, 27, 27)
                    .addComponent(jLabel12)
                    .addContainerGap(155, Short.MAX_VALUE)))
        );

        jPanelbotonesDetVenta.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Botones"));

        btnGuardardetvnt.setText("Pagar");
        btnGuardardetvnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardardetvntActionPerformed(evt);
            }
        });

        btnEliminardetvnt.setText("Eliminar Pago");
        btnEliminardetvnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminardetvntActionPerformed(evt);
            }
        });

        btnmostrardetvnt.setText("Mostrar");
        btnmostrardetvnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmostrardetvntActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelbotonesDetVentaLayout = new javax.swing.GroupLayout(jPanelbotonesDetVenta);
        jPanelbotonesDetVenta.setLayout(jPanelbotonesDetVentaLayout);
        jPanelbotonesDetVentaLayout.setHorizontalGroup(
            jPanelbotonesDetVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelbotonesDetVentaLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanelbotonesDetVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnmostrardetvnt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEliminardetvnt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGuardardetvnt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelbotonesDetVentaLayout.setVerticalGroup(
            jPanelbotonesDetVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelbotonesDetVentaLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(btnGuardardetvnt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminardetvnt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnmostrardetvnt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(28, 28, 28))
        );

        tblDetVenta.setModel(dtmDetVenta);
        tblDetVenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDetVentaMouseClicked(evt);
            }
        });
        jPaneltblDetVenta.setViewportView(tblDetVenta);

        jPanelBusquedaDetVenta.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Busqueda"));

        txtBusquedaDetVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBusquedaDetVentaActionPerformed(evt);
            }
        });

        btnBusquedaDetVenta.setText("Buscar");
        btnBusquedaDetVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBusquedaDetVentaActionPerformed(evt);
            }
        });

        jLabel14.setText("Buscar por:");

        jCBoxBusquedaDetVenta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nombre_Plataforma", "Codigo_Plataforma", "Mostrar_Plataforma" }));

        javax.swing.GroupLayout jPanelBusquedaDetVentaLayout = new javax.swing.GroupLayout(jPanelBusquedaDetVenta);
        jPanelBusquedaDetVenta.setLayout(jPanelBusquedaDetVentaLayout);
        jPanelBusquedaDetVentaLayout.setHorizontalGroup(
            jPanelBusquedaDetVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBusquedaDetVentaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBusquedaDetVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBusquedaDetVentaLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCBoxBusquedaDetVenta, 0, 156, Short.MAX_VALUE))
                    .addComponent(txtBusquedaDetVenta, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBusquedaDetVentaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnBusquedaDetVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanelBusquedaDetVentaLayout.setVerticalGroup(
            jPanelBusquedaDetVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBusquedaDetVentaLayout.createSequentialGroup()
                .addGroup(jPanelBusquedaDetVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jCBoxBusquedaDetVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBusquedaDetVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBusquedaDetVenta)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelDetVentaLayout = new javax.swing.GroupLayout(jPanelDetVenta);
        jPanelDetVenta.setLayout(jPanelDetVentaLayout);
        jPanelDetVentaLayout.setHorizontalGroup(
            jPanelDetVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDetVentaLayout.createSequentialGroup()
                .addGroup(jPanelDetVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPaneltblDetVenta, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDetVentaLayout.createSequentialGroup()
                        .addComponent(jPanelDatoscli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelbotonesDetVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanelBusquedaDetVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(39, 39, 39))
        );
        jPanelDetVentaLayout.setVerticalGroup(
            jPanelDetVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDetVentaLayout.createSequentialGroup()
                .addGroup(jPanelDetVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDetVentaLayout.createSequentialGroup()
                        .addGroup(jPanelDetVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelDetVentaLayout.createSequentialGroup()
                                .addComponent(jPanelbotonesDetVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14))
                            .addComponent(jPanelBusquedaDetVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanelDatoscli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jPaneltblDetVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelDetVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelDetVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(131, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    Object data[][] = new Object[0][0];
    Object datac[][] = new Object[0][0];
    
    private void btnGuardardetvntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardardetvntActionPerformed
        CODIGO_DETALLE_VENTA= txtcodigodetvnt.getText();
        ABONO= Integer.parseInt(txtabonodetvnt.getText());
        CODIGO_VENTA=txtcodvnt.getText();
        
        data = cv.consultarVentaCodigo(CODIGO_VENTA);
        datac = cdv.consultarDetalleVentaCodigo(CODIGO_DETALLE_VENTA);
        System.out.println("CODIGO_VENTA: " + data[0][0]);
        System.out.println("CODIGO_DETALLE_VENTA: " + datac[0][0]);

        try {
          if( data[0][0].toString().equals(CODIGO_VENTA) & datac[0][0]==null){
          boolean ejecuto = cdv.insertarDetalleVenta(CODIGO_DETALLE_VENTA, ABONO, cdv.saldo(cdv.valor_venta(CODIGO_VENTA), ABONO), CODIGO_VENTA);

             if (ejecuto){
            JOptionPane.showMessageDialog(this, "PAGO EXISTOSO!!","Guardar",JOptionPane.INFORMATION_MESSAGE);
                 actualizarTablaDetalleVenta(CODIGO_DETALLE_VENTA);
        }else {JOptionPane.showMessageDialog(this, "PAGO NO REALIZADO!!","CANCELAR",JOptionPane.ERROR_MESSAGE);}

            }
            if (data[0][0].toString().equals(CODIGO_VENTA) & datac[0][0].toString().equals(CODIGO_DETALLE_VENTA)) {
                
                
                boolean ejecuto2 = cdv.actualizarDetalleVenta(CODIGO_DETALLE_VENTA, cdv.abonoaux(cdv.valor_abono(CODIGO_VENTA), ABONO),
                        cdv.saldoaux(cdv.valor_saldo(CODIGO_VENTA), ABONO), CODIGO_VENTA);
                 if (ejecuto2){
            JOptionPane.showMessageDialog(this, "PAGO EXISTOSO!!","Guardar",JOptionPane.INFORMATION_MESSAGE);
                 actualizarTablaDetalleVenta(CODIGO_DETALLE_VENTA);
        }else {JOptionPane.showMessageDialog(this, "PAGO NO REALIZADO!!","CANCELAR",JOptionPane.ERROR_MESSAGE);}
            }
            if (data[0][0].toString().equals(CODIGO_VENTA) & datac[0][0]!=CODIGO_DETALLE_VENTA){
            
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "NO EXISTE VENTA","CANCELAR",JOptionPane.ERROR_MESSAGE);
            
//            boolean ejecuto = cdv.insertarDetalleVenta(codigo_det_venta, abono, cdv.saldo(cdv.valor_venta(codigo_venta), abono), codigo_venta);
//          System.out.println("CODIGO_VENTA: " + data[0][0]);
        }
        
        
       
    }//GEN-LAST:event_btnGuardardetvntActionPerformed

    private void btnEliminardetvntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminardetvntActionPerformed
        CODIGO_DETALLE_VENTA=txtcodigodetvnt.getText();
        int respuesta = JOptionPane.showConfirmDialog(this, "Desea Eliminar la PLATAFORMA "+CODIGO_DETALLE_VENTA+"?");
        boolean elimino = cp.eliminarPlataforma(CODIGO_DETALLE_VENTA);
       
        
        if (respuesta == JOptionPane.YES_OPTION){
            elimino = cp.eliminarPlataforma(CODIGO_DETALLE_VENTA);
                     
        }
    }//GEN-LAST:event_btnEliminardetvntActionPerformed

    private void btnmostrardetvntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmostrardetvntActionPerformed
        this.refrescarTblDetalleVenta();
        
        for (int i = 0; i < cdv.contarDetalleVenta(); i++) {
            System.out.println("COD DETALLE VENTA: " + data[i][0].toString()
                    + " ABONO: " + data[i][1].toString()
                    + " SALDO: " + data[i][2].toString()
                    + " COD VENTA: " + data[i][3].toString());
        }
        
    }//GEN-LAST:event_btnmostrardetvntActionPerformed

    private void tblDetVentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDetVentaMouseClicked
            
         
            int  sel = this.tblDetVenta.getSelectedRow();
            this.txtcodigodetvnt.setText(tblDetVenta.getValueAt(sel,0).toString());
            this.txtabonodetvnt.setText(tblDetVenta.getValueAt(sel,1).toString());
            this.txtcodvnt.setText(tblDetVenta.getValueAt(sel,2).toString());
            
            
            
            
    }//GEN-LAST:event_tblDetVentaMouseClicked

    private void txtBusquedaDetVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBusquedaDetVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBusquedaDetVentaActionPerformed

    private void btnBusquedaDetVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBusquedaDetVentaActionPerformed
        String Busqueda= txtBusquedaDetVenta.getText();
       Object dato[][]=cp.consultarPlataformaNombre(Busqueda);
       
       if ("Nombre_Plataforma".equals(jCBoxBusquedaDetVenta.getSelectedItem().toString())) {                
                 Object data[][] = cp.consultarPlataformaNombre(Busqueda);
                    dtmDetVenta= new DefaultTableModel(data,tablaDetVenta);
                    tblDetVenta.setModel(dtmDetVenta);                                         
       }else if("Codigo_Plataforma".equals(jCBoxBusquedaDetVenta.getSelectedItem().toString())){                
                 Object data[][] = cp.consultarPlataforma(Busqueda);
                    dtmDetVenta= new DefaultTableModel(data,tablaDetVenta);
                    tblDetVenta.setModel(dtmDetVenta);                    
       }else if ("Mostrar_Plataforma".equals(jCBoxBusquedaDetVenta.getSelectedItem().toString())){
                Object data[][] = cp.consultarPlataforma();
                    dtmDetVenta= new DefaultTableModel(data,tablaDetVenta);
                    tblDetVenta.setModel(dtmDetVenta);
       }else{JOptionPane.showMessageDialog(this, "Datos no Encontrados!!","Cancelar",JOptionPane.ERROR_MESSAGE);
       }
    }//GEN-LAST:event_btnBusquedaDetVentaActionPerformed

    private void txtabonodetvntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtabonodetvntActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtabonodetvntActionPerformed

    private void txtcodvntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcodvntActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodvntActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIDetalleVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIDetalleVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIDetalleVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIDetalleVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIDetalleVenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBusquedaDetVenta;
    private javax.swing.JButton btnEliminardetvnt;
    private javax.swing.JButton btnGuardardetvnt;
    private javax.swing.JButton btnmostrardetvnt;
    private javax.swing.JComboBox<String> jCBoxBusquedaDetVenta;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JPanel jPanelBusquedaDetVenta;
    private javax.swing.JPanel jPanelDatoscli;
    private javax.swing.JPanel jPanelDetVenta;
    private javax.swing.JPanel jPanelbotonesDetVenta;
    private javax.swing.JScrollPane jPaneltblDetVenta;
    private javax.swing.JTable tblDetVenta;
    private javax.swing.JTextField txtBusquedaDetVenta;
    private javax.swing.JTextField txtabonodetvnt;
    private javax.swing.JTextField txtcodigodetvnt;
    private javax.swing.JTextField txtcodvnt;
    // End of variables declaration//GEN-END:variables

    private void splite(String string) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
