/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author Mauricio
 */
public class GUILogin extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public GUILogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Jpanelregistrarse = new javax.swing.JPanel();
        txtNombrePer = new javax.swing.JTextField();
        txtIdePer = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtApellidoPer = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        JCBoxCargoPer = new javax.swing.JComboBox();
        jLabel17 = new javax.swing.JLabel();
        JCBTipoIdePer = new javax.swing.JComboBox();
        BtnOkPer = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        JpanelIngresar = new javax.swing.JPanel();
        txtUsuario = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtContraseña = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Jpanelregistrarse.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Ingresar Datos"));

        txtNombrePer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombrePerActionPerformed(evt);
            }
        });

        txtIdePer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdePerActionPerformed(evt);
            }
        });

        jLabel22.setText("Apellido:");

        txtApellidoPer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoPerActionPerformed(evt);
            }
        });

        jLabel23.setText("Cargo:");

        jLabel24.setText("Nombre");

        jLabel25.setText("Identificacion: ");

        JCBoxCargoPer.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Auxiliar", "Coordinador", "Ingeniero", "Tecnico", "Tecnologo" }));
        JCBoxCargoPer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCBoxCargoPerActionPerformed(evt);
            }
        });

        jLabel17.setText("Tipo:");

        JCBTipoIdePer.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "CC", "CE" }));
        JCBTipoIdePer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCBTipoIdePerActionPerformed(evt);
            }
        });

        BtnOkPer.setText("Ok");
        BtnOkPer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnOkPerActionPerformed(evt);
            }
        });

        jButton4.setText("Cancelar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JpanelregistrarseLayout = new javax.swing.GroupLayout(Jpanelregistrarse);
        Jpanelregistrarse.setLayout(JpanelregistrarseLayout);
        JpanelregistrarseLayout.setHorizontalGroup(
            JpanelregistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpanelregistrarseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JpanelregistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JpanelregistrarseLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BtnOkPer, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4))
                    .addGroup(JpanelregistrarseLayout.createSequentialGroup()
                        .addGroup(JpanelregistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel24)
                            .addComponent(jLabel17)
                            .addComponent(jLabel25)
                            .addComponent(jLabel23))
                        .addGap(52, 52, 52)
                        .addGroup(JpanelregistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JCBoxCargoPer, 0, 142, Short.MAX_VALUE)
                            .addGroup(JpanelregistrarseLayout.createSequentialGroup()
                                .addGroup(JpanelregistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JCBTipoIdePer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(JpanelregistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtApellidoPer, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                        .addComponent(txtNombrePer, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtIdePer, javax.swing.GroupLayout.Alignment.LEADING)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        JpanelregistrarseLayout.setVerticalGroup(
            JpanelregistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpanelregistrarseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JpanelregistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JCBTipoIdePer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JpanelregistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdePer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JpanelregistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombrePer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JpanelregistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtApellidoPer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JpanelregistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23)
                    .addComponent(JCBoxCargoPer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JpanelregistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnOkPer)
                    .addComponent(jButton4))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        JpanelIngresar.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Ingresar"));

        txtUsuario.setText("1088973525");
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });

        jLabel27.setText("Contraseña:");

        jLabel26.setText("Usuario:");

        jButton1.setText("Ok");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Registrarse!");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        txtContraseña.setText("1088973525");
        txtContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContraseñaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JpanelIngresarLayout = new javax.swing.GroupLayout(JpanelIngresar);
        JpanelIngresar.setLayout(JpanelIngresarLayout);
        JpanelIngresarLayout.setHorizontalGroup(
            JpanelIngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpanelIngresarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JpanelIngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JpanelIngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtUsuario)
                    .addGroup(JpanelIngresarLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(txtContraseña))
                .addContainerGap())
        );
        JpanelIngresarLayout.setVerticalGroup(
            JpanelIngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpanelIngresarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JpanelIngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JpanelIngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27)
                    .addComponent(txtContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JpanelIngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Jpanelregistrarse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JpanelIngresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(JpanelIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Jpanelregistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 656, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(163, 163, 163)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(163, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 421, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombrePerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombrePerActionPerformed
        txtApellidoPer.setEnabled(true);
        txtNombrePer.transferFocus();
    }//GEN-LAST:event_txtNombrePerActionPerformed

    private void txtIdePerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdePerActionPerformed
        txtNombrePer.setEnabled(true);
        txtIdePer.transferFocus();
    }//GEN-LAST:event_txtIdePerActionPerformed

    private void txtApellidoPerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoPerActionPerformed
        JCBoxCargoPer.setEnabled(true);
        txtApellidoPer.transferFocus();
    }//GEN-LAST:event_txtApellidoPerActionPerformed

    private void JCBoxCargoPerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCBoxCargoPerActionPerformed
        BtnOkPer.setEnabled(true);
        jButton4.setEnabled(true);
        JCBoxCargoPer.transferFocus();
    }//GEN-LAST:event_JCBoxCargoPerActionPerformed

    private void JCBTipoIdePerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCBTipoIdePerActionPerformed
        txtIdePer.setEnabled(true);
        JCBTipoIdePer.transferFocus();
    }//GEN-LAST:event_JCBTipoIdePerActionPerformed

    private void BtnOkPerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnOkPerActionPerformed

        try {
            Persona p = new Persona();
            String TIdeP = JCBTipoIdePer.getSelectedItem().toString();
            String IdeP = txtIdePer.getText();
            String NombreP = txtNombrePer.getText();
            String ApellidoP = txtApellidoPer.getText();
            String Carg = JCBoxCargoPer.getSelectedItem().toString();

            p.setAll( TIdeP,IdeP, NombreP,ApellidoP,Carg,IdeP);
            PDao.create(p);
            JOptionPane.showMessageDialog(null, "Bienvenido a Redytel: "+NombreP+" "+ ApellidoP+" ☺.");
            txtIde.setText(IdeP);
            txtBienvenido.setText("Bienvenido a Redytel: "+NombreP+" "+ ApellidoP+".");
            JPaneVenGas.setVisible(true);
            Jpanelregistrarse.setVisible(false);
            JpanelIngresar.setVisible(false);
        } catch (SQLException exguardarV) {
            JOptionPane.showMessageDialog(this, "Usuario Ya Rgistrado, Verificar Su Identificacion");
        }
    }//GEN-LAST:event_BtnOkPerActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        JCBTipoIdePer.setSelectedIndex(0);
        txtIdePer.setText("");
        txtNombrePer.setText("");
        txtApellidoPer.setText("");
        JCBoxCargoPer.setSelectedIndex(0);

    }//GEN-LAST:event_jButton4ActionPerformed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        txtContraseña.setEnabled(true);
        txtUsuario.transferFocus();
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            String usu=txtUsuario.getText();
            String pass=txtContraseña.getText();
            String Darwin="1061751297";
            String Mauricio="1088973525";
            Persona p=PDao.getObject(usu);

            if(p.getIdentificacion().equals(Mauricio)||p.getIdentificacion().equals(Darwin)){
                JOptionPane.showMessageDialog(null, "Bienvenido a Redytel: "+p.getNombre()+" "+ p.getApellido()+" ☺.");
                txtIde.setText(usu);
                txtBienvenido.setText("Bienvenido a Redytel: "+p.getNombre()+" "+ p.getApellido()+".");
                JpanelIngresar.setVisible(false);
                JPaneVenGas.setVisible(true);

            }else if(p.getIdentificacion().equals(usu)&&p.getCargo().equals(pass)){
                JOptionPane.showMessageDialog(null, "Bienvenido a Redytel: "+p.getNombre()+" "+ p.getApellido()+" ☺.");
                txtIde.setText(usu);
                txtBienvenido.setText("Bienvenido a Redytel: "+p.getNombre()+" "+ p.getApellido()+".");
                JPaneVenGas.setVisible(true);
                JpanelIngresar.setVisible(false);

            }else{
                JOptionPane.showMessageDialog(null, " Revisar los Datos\n Contraseña Incorrecta o Usuario Invalido\n De Lo Contrario Dar Clic En Registrarse!");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, " Revisar los Datos\n Contraseña Incorrecta o Usuario Invalido\n De Lo Contrario Dar Clic En Registrarse!");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Jpanelregistrarse.setVisible(true);
        JpanelIngresar.setVisible(false);
        JCBTipoIdePer.setEnabled(true);
        jButton2.transferFocus();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContraseñaActionPerformed
        jButton1.setEnabled(true);
        jButton2.setEnabled(true);
        txtContraseña.transferFocus();
    }//GEN-LAST:event_txtContraseñaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUILogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUILogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUILogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUILogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUILogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnOkPer;
    private javax.swing.JComboBox JCBTipoIdePer;
    private javax.swing.JComboBox JCBoxCargoPer;
    private javax.swing.JPanel JpanelIngresar;
    private javax.swing.JPanel Jpanelregistrarse;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtApellidoPer;
    private javax.swing.JPasswordField txtContraseña;
    private javax.swing.JTextField txtIdePer;
    private javax.swing.JTextField txtNombrePer;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
