/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Control.ControlCliente;
import Control.ControlPersona;
import Control.ControlPlataforma;
import Control.ControlVendedor;
import Control.ControlVenta;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author Mauricio
 */
public class GUIPlataforma extends javax.swing.JFrame {
  
    Control.ControlPlataforma cp=new ControlPlataforma();
    
    DefaultTableModel dtmPlataforma;
    
    
    
    String[] tablaPlataforma={"Codigo","Nombre"};
    
    
    String CODIGOPLT="";
    String NOMBREPLT="";
   
    
    public GUIPlataforma() {
        Object[][] data= cp.consultarPlataforma();
        
        
        dtmPlataforma=new DefaultTableModel(data, tablaPlataforma);
       
        initComponents();        
        
    }
    public void actualizarTablaPlataforma(String codigo){
        Object data[][] = cp.consultarPlataforma(codigo);
        dtmPlataforma= new DefaultTableModel(data,tablaPlataforma);
        tblPlt.setModel(dtmPlataforma);        
    }
    
    public void refrescarTblPlataforma(){
        Object[][] data= cp.consultarPlataforma();
        dtmPlataforma=new DefaultTableModel(data, tablaPlataforma);
        tblPlt.setModel(dtmPlataforma);
    }
    
    
   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelClientes = new javax.swing.JPanel();
        jPanelDatoscli = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        txtcodigoplt = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtnombreplt = new javax.swing.JTextField();
        jPanelbotonescli = new javax.swing.JPanel();
        btnGuardarPlt = new javax.swing.JButton();
        btnEliminarPlt = new javax.swing.JButton();
        btnModificarPlt = new javax.swing.JButton();
        btnmostrarPlt = new javax.swing.JButton();
        jPaneltblPlt = new javax.swing.JScrollPane();
        tblPlt = new javax.swing.JTable();
        jPanelBusquedaclie = new javax.swing.JPanel();
        txtBusquedaPlt = new javax.swing.JTextField();
        btnBusquedaPlt = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jCBoxBusquedaPlt = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelClientes.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Cliente"));

        jPanelDatoscli.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Ingresar Datos"));

        jLabel12.setText("Codigo:");

        jLabel13.setText("Nombre:");

        javax.swing.GroupLayout jPanelDatoscliLayout = new javax.swing.GroupLayout(jPanelDatoscli);
        jPanelDatoscli.setLayout(jPanelDatoscliLayout);
        jPanelDatoscliLayout.setHorizontalGroup(
            jPanelDatoscliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatoscliLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addGap(10, 10, 10)
                .addGroup(jPanelDatoscliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtcodigoplt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                    .addComponent(txtnombreplt, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(jPanelDatoscliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelDatoscliLayout.createSequentialGroup()
                    .addGap(6, 6, 6)
                    .addComponent(jLabel12)
                    .addContainerGap(199, Short.MAX_VALUE)))
        );
        jPanelDatoscliLayout.setVerticalGroup(
            jPanelDatoscliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDatoscliLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(txtcodigoplt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatoscliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtnombreplt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(126, Short.MAX_VALUE))
            .addGroup(jPanelDatoscliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelDatoscliLayout.createSequentialGroup()
                    .addGap(27, 27, 27)
                    .addComponent(jLabel12)
                    .addContainerGap(155, Short.MAX_VALUE)))
        );

        jPanelbotonescli.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Botones"));

        btnGuardarPlt.setText("Guardar");
        btnGuardarPlt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarPltActionPerformed(evt);
            }
        });

        btnEliminarPlt.setText("Eliminar");
        btnEliminarPlt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarPltActionPerformed(evt);
            }
        });

        btnModificarPlt.setText("Modificar");
        btnModificarPlt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarPltActionPerformed(evt);
            }
        });

        btnmostrarPlt.setText("Refrescar");
        btnmostrarPlt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmostrarPltActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelbotonescliLayout = new javax.swing.GroupLayout(jPanelbotonescli);
        jPanelbotonescli.setLayout(jPanelbotonescliLayout);
        jPanelbotonescliLayout.setHorizontalGroup(
            jPanelbotonescliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelbotonescliLayout.createSequentialGroup()
                .addGroup(jPanelbotonescliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelbotonescliLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanelbotonescliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnmostrarPlt, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                            .addComponent(btnEliminarPlt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnModificarPlt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanelbotonescliLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnGuardarPlt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelbotonescliLayout.setVerticalGroup(
            jPanelbotonescliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelbotonescliLayout.createSequentialGroup()
                .addComponent(btnGuardarPlt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminarPlt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnModificarPlt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnmostrarPlt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        tblPlt.setModel(dtmPlataforma);
        tblPlt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPltMouseClicked(evt);
            }
        });
        jPaneltblPlt.setViewportView(tblPlt);

        jPanelBusquedaclie.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Busqueda"));

        txtBusquedaPlt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBusquedaPltActionPerformed(evt);
            }
        });

        btnBusquedaPlt.setText("Buscar");
        btnBusquedaPlt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBusquedaPltActionPerformed(evt);
            }
        });

        jLabel14.setText("Buscar por:");

        jCBoxBusquedaPlt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nombre_Plataforma", "Codigo_Plataforma", "Mostrar_Plataforma" }));

        javax.swing.GroupLayout jPanelBusquedaclieLayout = new javax.swing.GroupLayout(jPanelBusquedaclie);
        jPanelBusquedaclie.setLayout(jPanelBusquedaclieLayout);
        jPanelBusquedaclieLayout.setHorizontalGroup(
            jPanelBusquedaclieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBusquedaclieLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBusquedaclieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBusquedaclieLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCBoxBusquedaPlt, 0, 156, Short.MAX_VALUE))
                    .addComponent(txtBusquedaPlt, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBusquedaclieLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnBusquedaPlt, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanelBusquedaclieLayout.setVerticalGroup(
            jPanelBusquedaclieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBusquedaclieLayout.createSequentialGroup()
                .addGroup(jPanelBusquedaclieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jCBoxBusquedaPlt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBusquedaPlt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBusquedaPlt)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelClientesLayout = new javax.swing.GroupLayout(jPanelClientes);
        jPanelClientes.setLayout(jPanelClientesLayout);
        jPanelClientesLayout.setHorizontalGroup(
            jPanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelClientesLayout.createSequentialGroup()
                .addComponent(jPanelDatoscli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelbotonescli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelBusquedaclie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(39, 39, 39))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPaneltblPlt, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelClientesLayout.setVerticalGroup(
            jPanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelClientesLayout.createSequentialGroup()
                .addGroup(jPanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelClientesLayout.createSequentialGroup()
                        .addGroup(jPanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelClientesLayout.createSequentialGroup()
                                .addComponent(jPanelbotonescli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14))
                            .addComponent(jPanelBusquedaclie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(32, 32, 32))
                    .addGroup(jPanelClientesLayout.createSequentialGroup()
                        .addComponent(jPanelDatoscli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jPaneltblPlt, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(119, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarPltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarPltActionPerformed
        CODIGOPLT= txtcodigoplt.getText();
        NOMBREPLT= txtnombreplt.getText();
        
        boolean insertop = cp.insertarPlataforma(CODIGOPLT, NOMBREPLT);
        
        if (insertop){
            JOptionPane.showMessageDialog(this, "Datos Almacenados!!","Guardar",JOptionPane.INFORMATION_MESSAGE);
            actualizarTablaPlataforma(CODIGOPLT);
        }else {JOptionPane.showMessageDialog(this, "Datos no Almacenados!!","Guardar",JOptionPane.ERROR_MESSAGE);}
    }//GEN-LAST:event_btnGuardarPltActionPerformed

    private void btnEliminarPltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarPltActionPerformed
        CODIGOPLT=txtcodigoplt.getText();
        int respuesta = JOptionPane.showConfirmDialog(this, "Desea Eliminar la PLATAFORMA "+CODIGOPLT+"?");
        boolean elimino = cp.eliminarPlataforma(CODIGOPLT);
       
        
        if (respuesta == JOptionPane.YES_OPTION){
            elimino = cp.eliminarPlataforma(CODIGOPLT);
                     
        }
    }//GEN-LAST:event_btnEliminarPltActionPerformed

    private void btnModificarPltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarPltActionPerformed
       CODIGOPLT= txtcodigoplt.getText();
        NOMBREPLT= txtnombreplt.getText();
        
        boolean insertop = cp.actualizarPlataforma(CODIGOPLT, NOMBREPLT);
              if (insertop){
            JOptionPane.showMessageDialog(this, "Datos Modificados!!","guardar",JOptionPane.INFORMATION_MESSAGE);
            actualizarTablaPlataforma(CODIGOPLT);
        }else {JOptionPane.showMessageDialog(this, "Datos no Almacenados!!","guardar",JOptionPane.ERROR_MESSAGE);}
    }//GEN-LAST:event_btnModificarPltActionPerformed

    private void btnmostrarPltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmostrarPltActionPerformed
        this.refrescarTblPlataforma();
    }//GEN-LAST:event_btnmostrarPltActionPerformed

    private void tblPltMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPltMouseClicked
            
         
            int  sel = this.tblPlt.getSelectedRow();
            this.txtcodigoplt.setText(tblPlt.getValueAt(sel,0).toString());
            this.txtnombreplt.setText(tblPlt.getValueAt(sel,1).toString());
           
    }//GEN-LAST:event_tblPltMouseClicked

    private void txtBusquedaPltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBusquedaPltActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBusquedaPltActionPerformed

    private void btnBusquedaPltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBusquedaPltActionPerformed
        String Busqueda= txtBusquedaPlt.getText();
       Object dato[][]=cp.consultarPlataformaNombre(Busqueda);
       
       if ("Nombre_Plataforma".equals(jCBoxBusquedaPlt.getSelectedItem().toString())) {                
                 Object data[][] = cp.consultarPlataformaNombre(Busqueda);
                    dtmPlataforma= new DefaultTableModel(data,tablaPlataforma);
                    tblPlt.setModel(dtmPlataforma);                                         
       }else if("Codigo_Plataforma".equals(jCBoxBusquedaPlt.getSelectedItem().toString())){                
                 Object data[][] = cp.consultarPlataforma(Busqueda);
                    dtmPlataforma= new DefaultTableModel(data,tablaPlataforma);
                    tblPlt.setModel(dtmPlataforma);                    
       }else if ("Mostrar_Plataforma".equals(jCBoxBusquedaPlt.getSelectedItem().toString())){
                Object data[][] = cp.consultarPlataforma();
                    dtmPlataforma= new DefaultTableModel(data,tablaPlataforma);
                    tblPlt.setModel(dtmPlataforma);
       }else{JOptionPane.showMessageDialog(this, "Datos no Encontrados!!","Cancelar",JOptionPane.ERROR_MESSAGE);
       }
    }//GEN-LAST:event_btnBusquedaPltActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIPlataforma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIPlataforma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIPlataforma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIPlataforma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIPlataforma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBusquedaPlt;
    private javax.swing.JButton btnEliminarPlt;
    private javax.swing.JButton btnGuardarPlt;
    private javax.swing.JButton btnModificarPlt;
    private javax.swing.JButton btnmostrarPlt;
    private javax.swing.JComboBox<String> jCBoxBusquedaPlt;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JPanel jPanelBusquedaclie;
    private javax.swing.JPanel jPanelClientes;
    private javax.swing.JPanel jPanelDatoscli;
    private javax.swing.JPanel jPanelbotonescli;
    private javax.swing.JScrollPane jPaneltblPlt;
    private javax.swing.JTable tblPlt;
    private javax.swing.JTextField txtBusquedaPlt;
    private javax.swing.JTextField txtcodigoplt;
    private javax.swing.JTextField txtnombreplt;
    // End of variables declaration//GEN-END:variables

    private void splite(String string) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
